export const Icons = {
  Automaton: require( './automaton.svg' ).default,
  AutomatonA: require( './automaton-a.svg' ).default,
  Channel: require( './channel.svg' ).default,
  Close: require( './close.svg' ).default,
  Cog: require( './cog.svg' ).default,
  Curve: require( './curve.svg' ).default,
  DopeSheet: require( './dope-sheet.svg' ).default,
  Error: require( './error.svg' ).default,
  Info: require( './info.svg' ).default,
  Pause: require( './pause.svg' ).default,
  Play: require( './play.svg' ).default,
  Plus: require( './plus.svg' ).default,
  Power: require( './power.svg' ).default,
  Redo: require( './redo.svg' ).default,
  Save: require( './save.svg' ).default,
  Snap: require( './snap.svg' ).default,
  Undo: require( './undo.svg' ).default,
  Warning: require( './warning.svg' ).default,
};
