export declare const Colors: {
    black: string;
    white: string;
    back1: string;
    back2: string;
    back3: string;
    back4: string;
    back5: string;
    fore: string;
    foresub: string;
    foredark: string;
    gray: string;
    accentbright: string;
    accent: string;
    accentdark: string;
    fx: string;
    error: string;
    errorBright: string;
    warning: string;
    info: string;
};
