# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2

jobs:
  fetch:
    docker: &docker
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      - run:
          name: Node version
          command: node -v
      - run:
          name: Fetch deps
          command: yarn
      - save_cache:
          key: deps-{{ checksum "package.json" }}
          paths:
            - node_modules

  build:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      - run:
          name: Build
          command: yarn build
      - store_artifacts:
          path: dist

workflows:
  version: 2
  fuckery:
    jobs:
      - fetch
      - build:
          requires:
            - fetch
