export declare const Icons: {
    Automaton: "svg";
    AutomatonA: "svg";
    Channel: "svg";
    Close: "svg";
    Cog: "svg";
    Curve: "svg";
    DopeSheet: "svg";
    Error: "svg";
    Info: "svg";
    Pause: "svg";
    Play: "svg";
    Plus: "svg";
    Power: "svg";
    Redo: "svg";
    Save: "svg";
    Snap: "svg";
    Undo: "svg";
    Warning: "svg";
};
