name: Inspect automaton
on:
  push:
    paths:
      - '**'
      - '!packages/**'
      - 'packages/automaton/**'
defaults:
  run:
    shell: bash
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Fetch Deps
      run: yarn
  lint:
    runs-on: ubuntu-latest
    needs: fetch
    defaults:
      run:
        working-directory: packages/automaton
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Lint
      run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: fetch
    defaults:
      run:
        working-directory: packages/automaton
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Test
      run: yarn test
  build:
    runs-on: ubuntu-latest
    needs: fetch
    defaults:
      run:
        working-directory: packages/automaton
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build
      run: yarn build
    - name: Upload Builds
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          packages/automaton/dist/
          packages/automaton/types/
          packages/automaton/ts*/
  docs:
    runs-on: ubuntu-latest
    needs: fetch
    defaults:
      run:
        working-directory: packages/automaton
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build Docs
      run: yarn docs
    - name: Upload Docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: |
          packages/automaton/docs/
