name: Publish gh-pages
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Fetch Deps
      run: yarn
  build-automaton:
    runs-on: ubuntu-latest
    needs: fetch
    defaults:
      run:
        working-directory: packages/automaton
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build
      run: yarn build
    - name: Upload Builds
      uses: actions/upload-artifact@v2
      with:
        name: build-automaton
        path: |
          packages/automaton/dist/
          packages/automaton/types/
          packages/automaton/ts*/
  docs-automaton:
    runs-on: ubuntu-latest
    needs: fetch
    defaults:
      run:
        working-directory: packages/automaton
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build Docs
      run: yarn docs
    - name: Upload Docs
      uses: actions/upload-artifact@v2
      with:
        name: docs-automaton
        path: |
          packages/automaton/docs/
  build-automaton-fxs:
    runs-on: ubuntu-latest
    needs: build-automaton
    defaults:
      run:
        working-directory: packages/automaton-fxs
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: build-automaton
        path: packages/automaton
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build
      run: yarn build
    - name: Upload Builds
      uses: actions/upload-artifact@v2
      with:
        name: build-automaton-fxs
        path: |
          packages/automaton-fxs/dist/
          packages/automaton-fxs/types/
          packages/automaton-fxs/ts*/
  build-automaton-with-gui:
    runs-on: ubuntu-latest
    needs: build-automaton
    defaults:
      run:
        working-directory: packages/automaton-with-gui
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: build-automaton
        path: packages/automaton
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build
      run: yarn build
    - name: Upload Builds
      uses: actions/upload-artifact@v2
      with:
        name: build-automaton-with-gui
        path: |
          packages/automaton-with-gui/dist/
          packages/automaton-with-gui/types/
          packages/automaton-with-gui/ts*/
  docs-automaton-with-gui:
    runs-on: ubuntu-latest
    needs: build-automaton
    defaults:
      run:
        working-directory: packages/automaton-with-gui
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: build-automaton
        path: packages/automaton
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build Docs
      run: yarn docs
    - name: Upload Docs
      uses: actions/upload-artifact@v2
      with:
        name: docs-automaton-with-gui
        path: |
          packages/automaton-with-gui/docs/
  pages:
    runs-on: ubuntu-latest
    needs:
      - build-automaton
      - docs-automaton
      - build-automaton-fxs
      - build-automaton-with-gui
      - docs-automaton-with-gui
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Setup Pages
      run: |
        mkdir pages

        mv README.md pages

        mkdir pages/automaton
        mv artifacts/build-automaton/* pages/automaton
        mv artifacts/docs-automaton/* pages/automaton
        mv packages/automaton/README.md pages/automaton

        mkdir pages/automaton-fxs
        mv artifacts/build-automaton-fxs/* pages/automaton-fxs
        mv packages/automaton-fxs/README.md pages/automaton-fxs

        mkdir pages/automaton-with-gui
        mv artifacts/build-automaton-with-gui/* pages/automaton-with-gui
        mv artifacts/docs-automaton-with-gui/* pages/automaton-with-gui
        mv packages/automaton-with-gui/index.html pages/automaton-with-gui
        mv packages/automaton-with-gui/playground-examples pages/automaton-with-gui
        mv packages/automaton-with-gui/README.md pages/automaton-with-gui
    - name: Publish gh-pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: pages
