name: Inspect
on: [push]
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Fetch Deps
      shell: bash
      run: yarn --frozen-lockfile
  lint:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Lint
      shell: bash
      run: npx lerna run lint
  test:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Test
      shell: bash
      run: npx lerna run test
  build:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build
      shell: bash
      run: npx lerna run build
    - name: Upload Builds
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
    - name: Upload Types
      uses: actions/upload-artifact@v1
      with:
        name: types
        path: types
  docs:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build Docs
      shell: bash
      run: npx lerna run docs
    - name: Upload Docs
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: ./docs
